- README.md
> fix(*): fix link in README

- build/webpack.dist.config.babel.js
- src/versions.json
> feat(build): output everything at the root folder

- yarn.lock
Signed-off-by: Antoine Leblanc <antoine.leblanc@corp.ovh.com>
> chore(yarn): update yarn.lock file.

- src/documentation/contributing.md
- src/documentation/documentation.routes.js
- src/documentation/urls.md
You can test it here: http://feature_urls.ui-kit.ovh/#!/documentation/contributing
> feat(documentation): explain new urls formats

- src/ovh-ui-kit/ovh-ui-kit.config.json
- src/ovh-ui-kit/ovh-ui-kit.routes.js
You can see it running here: http://feature_groups_items_demo.ui-kit.ovh/#!/ovh-ui-kit/introduction
> feat(ovh-ui-kit): group items together using config file and state

- build/webpack.base.config.js
- build/webpack.dev.config.js
- build/webpack.dist.config.babel.js
> bugfix(build): support less hmr on dev build

- src/documentation/component-status.md
> docs(status): add documentation for deprecated tag

- build/webpack.dev.config.js
> chore: add hot reload for ui-angular part

- package.json
- src/index.js
- src/ovh-ui-angular/ovh-ui-angular.routes.js
- src/ovh-ui-angular/show-current-value-in-popup.controller.js
- yarn.lock
> feat: Integrate ovh-ui-angular

- src/ovh-ui-angular/decisions.md
- src/ovh-ui-angular/ovh-ui-angular.routes.js
http://feat_decisions.ui-kit.ovh/#!/oui-angular/decisions
> doc(ovh-ui-angular): architectural decisions explained

- src/ovh-ui-angular/decisions.md
> doc(decisions): keep code as simple as possible

- build/webpack.base.config.js
- build/webpack.dist.config.babel.js
> fix(build): hash for app js and css files

- package.json
> chore(package): update dependencies links

- src/ovh-ui-angular/ovh-ui-angular.config.json
- src/ovh-ui-kit/ovh-ui-kit.config.json
http://spinner_staging.ui-kit.ovh
Requires https://github.com/ovh-ux/ovh-ui-kit/pull/109 and https://github.com/ovh-ux/ovh-ui-angular/pull/31
> feat(oui-loader): rename to oui-spinner

- src/functional-tests/datagrid-local.html
- src/functional-tests/datagrid-remote.html
- src/functional-tests/functional-tests.routes.js
- src/functional-tests/watchers-results.md
- src/index.js
- src/ovh-ui-angular/controllers/datagrid.controller.js
New pages are:
- http://performance_watchers_staging.ui-kit.ovh/#!/tests/functional/datagrid/local/small
- http://performance_watchers_staging.ui-kit.ovh/#!/tests/functional/datagrid/local/large
- http://performance_watchers_staging.ui-kit.ovh/#!/tests/functional/datagrid/remote/small
- http://performance_watchers_staging.ui-kit.ovh/#!/tests/functional/datagrid/remote/large
See the `watchers-results.md` file for results about those functional tests pages.
> refactor(oui-datagrid): functional tests with improvements

- src/ovh-ui-angular/ovh-ui-angular.config.json
> feat(ovh-ui-angular): reorganize components

- src/ovh-ui-kit/ovh-ui-kit.config.json
> feat(*): update components groups

- CHANGELOG.md
- src/documentation/documentation.routes.js
- src/ovh-ui-angular/ovh-ui-angular.routes.js
- src/ovh-ui-kit/ovh-ui-kit.routes.js
http://doc_changelog_staging.ui-kit.ovh/#!/documentation/changelog
http://doc_changelog_staging.ui-kit.ovh/#!/ovh-ui-kit/changelog
http://doc_changelog_staging.ui-kit.ovh/#!/oui-angular/changelog
Please review those PRs before: 
- https://github.com/ovh-ux/ovh-ui-kit/pull/124 
- https://github.com/ovh-ux/ovh-ui-angular/pull/55
- https://github.com/ovh-ux/ovh-documentation-toolkit/pull/18
> doc(changelog): new file and sections

- build/webpack.base.config.js
http://fix_webpack_exclusion.ui-kit.ovh/#!/documentation/introduction
> fix(build): file exclusion on windows paths

- CHANGELOG.md
> doc(changelog): add ovh-ui-kit fix

- package.json
- src/index.js
- src/ovh-ui-angular/controllers/index.js
- src/ovh-ui-angular/controllers/navbar.controller.js
- src/ovh-ui-angular/ovh-ui-angular.config.json
- yarn.lock
Related:
https://github.com/ovh-ux/ovh-ui-angular/pull/63
https://github.com/ovh-ux/ovh-ui-kit/pull/132
Staging: http://build_oui_navbar.ui-kit.ovh/#!/oui-angular/navbar
> chore(*): update for oui-navbar component

- src/ovh-ui-angular/ovh-ui-angular.config.json
> doc(menu): add modal to menu

- src/ovh-ui-angular/controllers/navbar.controller.js
UU-714
Linked to https://github.com/ovh-ux/ovh-ui-angular/pull/92
> chore(navbar): update for the toggler-links attribute

- src/ovh-ui-angular/ovh-ui-angular.config.json
> feat(textarea): add new component in menu

- src/ovh-ui-angular/controllers/field.controller.js
- src/ovh-ui-angular/controllers/index.js
- src/ovh-ui-angular/ovh-ui-angular.config.json
UU-729
Angular related: https://github.com/ovh-ux/ovh-ui-angular/pull/97
Style related: https://github.com/ovh-ux/ovh-ui-kit/pull/154
> Select integration in field

- .babelrc
- package.json
- yarn.lock
**Merge and release ovh-documentation-toolkit (https://github.com/ovh-ux/ovh-documentation-toolkit/pull/20) before**
> Remove babel-preset-es2015

- src/ovh-ui-angular/controllers/index.js
- src/ovh-ui-angular/controllers/search.controller.js
- src/ovh-ui-angular/ovh-ui-angular.config.json
UU-568
http://build_oui_search.ui-kit.ovh/#!/oui-angular/search
Linked to
https://github.com/ovh-ux/ovh-ui-angular/pull/105
https://github.com/ovh-ux/ovh-ui-kit/pull/158
> feat(oui-search): add oui-search component

- package.json
- src/ovh-ui-angular/controllers/criteria-adder.controller.js
- src/ovh-ui-angular/controllers/fixtures/criteria-adder.data.json
- src/ovh-ui-angular/controllers/index.js
- src/ovh-ui-angular/ovh-ui-angular.config.json
UU-744
http://build_oui_criteria_adder.ui-kit.ovh/#!/oui-angular/criteria-adder
Related to
https://github.com/ovh-ux/ovh-ui-kit/pull/165
https://github.com/ovh-ux/ovh-ui-angular/pull/115
> feat(oui-criteria-adder): add oui-criteria-adder component

- src/ovh-ui-angular/controllers/chips.controller.js
- src/ovh-ui-angular/controllers/fixtures/chips.data.json
- src/ovh-ui-angular/controllers/index.js
- src/ovh-ui-angular/ovh-ui-angular.config.json
- src/ovh-ui-kit/ovh-ui-kit.config.json
UU-727
http://build_oui_chips.ui-kit.ovh/#!/oui-angular/chips
http://build_oui_chips.ui-kit.ovh/#!/ovh-ui-kit/chip
Related to:
https://github.com/ovh-ux/ovh-ui-kit/pull/166
https://github.com/ovh-ux/ovh-ui-angular/pull/122
> feat(oui-chips): add oui-chips component

- build/webpack.dist.config.babel.js
- build/webpack.staging.config.babel.js
- package.json
> chore: always build ovh-ui-angular

- src/ovh-ui-angular/controllers/calendar.controller.js
- src/ovh-ui-angular/controllers/index.js
- src/ovh-ui-angular/ovh-ui-angular.config.json
UU-562
http://build_oui_calendar.ui-kit.ovh/#!/oui-angular/calendar
Related to
https://github.com/ovh-ux/ovh-ui-kit/pull/172
https://github.com/ovh-ux/ovh-ui-angular/pull/128
> feat(oui-calendar): add oui-calendar component

- package.json
- src/index.less
- yarn.lock
https://github.com/ovh-ux/ovh-ui-kit/pull/177
https://github.com/ovh-ux/ovh-ui-angular/pull/142
> chore(oui-calendar): add flatpickr style

- build/webpack.base.config.js
- package.json
- src/ovh-ui-angular/controllers/datagrid.controller.js
- src/ovh-ui-angular/controllers/fixtures/criteria-adder.data.json
- yarn.lock
UU-746
See:
https://github.com/ovh-ux/ovh-ui-kit/pull/178
https://github.com/ovh-ux/ovh-ui-angular/pull/140
Staging: https://ovh_ui_kit_documentation-feat_datagrid_filter_operators_staging.uxci.ovh/#!/oui-angular/datagrid
> docs(oui-datagrid): add demo data

- src/ovh-ui-angular/controllers/select.controller.js
Add Events examples
http://build_oui_select.ui-kit.ovh
Linked to : 
ovh-ux/ovh-ui-angular/pull/163
> Add oui-select events examples

- README.md
Help user to understand how to reorganize components using json files and how components auto discovery works.
> docs: help on components reorganization

- package.json
- src/index.js
- yarn.lock
**https://github.com/ovh-ux/ovh-documentation-toolkit/pull/27/files must be merged BEFORE.**
- Update Ui-Router to version 1
- Use the new navbar
Demo: http://chore_update_ui_router_staging.ui-kit.ovh
> chore: update ui-router

- package.json
- yarn.lock
Update dependencies and yarn lock
> chore: bump version of dependencies

- src/ovh-ui-angular/controllers/datagrid.controller.js
UK-17
Staging: http://feat_datagrid_update_staging.ui-kit.ovh/#!/oui-angular/datagrid
Angular PR: https://github.com/ovh-ux/ovh-ui-angular/pull/194
> Datagrid: refresh

- src/ovh-ui-angular/ovh-ui-angular.config.json
- src/ovh-ui-kit/ovh-ui-kit.config.json
UU-836
Collapsible component added.
**Linked to**
https://github.com/ovh-ux/ovh-ui-kit/pull/197
https://github.com/ovh-ux/ovh-ui-angular/pull/173
> feat(oui-collapsible): collapsible component addition

- src/ovh-ui-angular/ovh-ui-angular.config.json
- src/ovh-ui-kit/ovh-ui-kit.config.json
add clipboard to others
cui clipboard to oui
Demo: http://feature_oui_clipboard_build.ui-kit.ovh/#!/oui-angular/clipboard
> feat: oui clipboard

- build/loaders/markdown-renderer.js
- src/index.less
- Add `oui-doc-preview` classname around documentation previews
- Add margin on previews
> feat(oui-doc): add margin on previews

- src/ovh-ui-angular/controllers/datagrid.controller.js
SCDC-744
PR Angular: https://github.com/ovh-ux/ovh-ui-angular/pull/196
PR Style: https://github.com/ovh-ux/ovh-ui-kit/pull/214
Staging: http://feature_datagrid_customize_staging.ui-kit.ovh//#!/oui-angular/datagrid
> docs(oui-datagrid): add methods for datagrid documentation

- src/ovh-ui-angular/ovh-ui-angular.config.json
- src/ovh-ui-kit/ovh-ui-kit.config.json
`/#!/ovh-ui-kit/page-header` @ `ovh_ui_kit_documentation-feat_page_header_staging`
**Linked to**
https://github.com/ovh-ux/ovh-ui-angular/pull/204
https://github.com/ovh-ux/ovh-ui-kit/pull/219
> feat(page-header): add page-header component

- src/ovh-ui-angular/ovh-ui-angular.config.json
- src/ovh-ui-kit/ovh-ui-kit.config.json
> feat(oui-tile): group

- src/ovh-ui-angular/ovh-ui-angular.config.json
- src/ovh-ui-kit/ovh-ui-kit.config.json
/#!/ovh-ui-angular/header-tabs @ ovh_ui_kit_documentation-feat_oui_header_tabs_staging
Linked to
ovh-ux/ovh-ui-angular#209
ovh-ux/ovh-ui-kit#221
> feat(header-tabs): add header-tabs component

- src/ovh-ui-angular/ovh-ui-angular.config.json
/#!/ovh-ui-angular/switch @ ovh_ui_kit_documentation-feat_oui_switch_staging
Linked to
https://github.com/ovh-ux/ovh-ui-angular/pull/191
https://github.com/ovh-ux/ovh-ui-kit/pull/211
> feat: oui switch

- src/index.less
- yarn.lock
Avoid having interference from BS style with OUI style
> style: update to use only bootstrap grid

- build/loaders/markdown-renderer.js
Linked to https://github.com/ovh-ux/ovh-ui-kit/pull/282
> style: rename oui-header as oui-heading

- src/ovh-ui-angular/controllers/select.controller.js
Related to : https://github.com/ovh-ux/ovh-ui-angular/pull/291
> feat(oui-select): allow options to be disabled

- src/ovh-ui-angular/controllers/index.js
- src/ovh-ui-angular/controllers/inline-adder.controller.js
- src/ovh-ui-angular/ovh-ui-angular.config.json
UK-16
Related to
https://github.com/ovh-ux/ovh-ui-kit/pull/302
https://github.com/ovh-ux/ovh-ui-angular/pull/304
> feat(oui-inline-adder): add inline-adder component

- src/ovh-ui-angular/controllers/dual-list.controller.js
- src/ovh-ui-angular/controllers/index.js
- src/ovh-ui-angular/ovh-ui-angular.config.json
- yarn.lock
UK-15
Related to
https://github.com/ovh-ux/ovh-ui-kit/pull/307
https://github.com/ovh-ux/ovh-ui-angular/pull/311
> feat(oui-dual-list): add dual-list component

- src/ovh-ui-angular/ovh-ui-angular.config.json
UK-62
Related to
* https://github.com/ovh-ux/ovh-ui-kit/pull/311
* https://github.com/ovh-ux/ovh-ui-angular/pull/319
> feat(oui-tabs): add tabs component

- src/ovh-ui-angular/ovh-ui-angular.config.json
UK-60
Related to
* https://github.com/ovh-ux/ovh-ui-angular/pull/324
* https://github.com/ovh-ux/ovh-ui-kit/pull/312
> feat(oui-file): add file component

- src/ovh-ui-angular/controllers/index.js
- src/ovh-ui-angular/controllers/timepicker.controller.js
- src/ovh-ui-angular/ovh-ui-angular.config.json
UK-61
Related to:
* https://github.com/ovh-ux/ovh-ui-kit/pull/327
* https://github.com/ovh-ux/ovh-ui-angular/pull/344
> feat(oui-timepicker): add timepicker component

- src/ovh-ui-angular/controllers/pagination.controller.js
**Related to**
- https://github.com/ovh-ux/ovh-ui-angular/pull/358
- https://github.com/ovh-ux/ovh-ui-kit/pull/342
> fix(oui-pagination): add input search when huge amount of pages

- src/ovh-ui-angular/controllers/datagrid.controller.js
> feat(oui-datagrid): add pagination change example
